/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shikoooooooo (https://sketchfab.com/shikoooooooo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blackhole-32f978d0e7354af293fa498f2998b14c
Title: Blackhole
*/
import React, { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";

import blackHole_scene from "../assets/3D_Models/blackhole.glb";

const BlackHole = () => {
  const blackHole_ref = useRef();
  // Load the 3D model and animations from the provided glb file
  const { scene, animations } = useGLTF(blackHole_scene);
  // Get access to the animations for the 3D model
  const { actions } = useAnimations(animations, blackHole_ref);

  // Play the "CINEMA_4D_Main" animation when the component mounts
  // Note: Animation names can be found on the Sketchfab website where the 3D model is hosted.
  useEffect(() => {
    const action = actions["CINEMA_4D_Main"];
    if (action) {
      action.timeScale = 3; // change the animation speed
      action.play();
    }
  }, []);

  return (
    <mesh
      position={[10.5, 3.5, -5]}
      scale={[0.25, 0.25, 0.25]}
      rotation={[0, 1, 2]}
      ref={blackHole_ref}
    >
      <primitive object={scene} />
    </mesh>
  );
};

export default BlackHole;
