/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BlueMesh (https://sketchfab.com/VapTor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/x-wing-04b0147bd4234e61ba21bbf7a73ceecc
Title: X -WING
*/
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

import spaceship_scene from "../assets/3d/spaceship.glb";

const SpaceShip = ({ isRotating, ...props }) => {
  const spaceship_ref = useRef();
  // Load the 3D model and its animations
  const { scene, animations, materials } = useGLTF(spaceship_scene);
  // Get animation actions associated with the 3D model
  const { actions } = useAnimations(animations, spaceship_ref);

  // Use an effect to control the 3D model's animation based on 'isRotating'
  // Note: Animation names can be found on the Sketchfab website where the 3D model is hosted.
  useEffect(() => {
    const action = actions["Take 01"];
    if (action) {
      action.timeScale = 2; // change the animation speed
      const Circle002 = materials.BakedCycles; // gets the properties(BakedCycles) of the 3D model for the node "Circle.002"
      if (isRotating) {
        action.play();
        if (Circle002) {
          Circle002.transparent = false;
        }
      } else {
        action.stop();
        if (Circle002) {
          Circle002.opacity = 0;
          Circle002.transparent = true;
        }
      }
    }
  }, [actions, isRotating]);

  return (
    <mesh {...props} ref={spaceship_ref}>
      <primitive object={scene} />
    </mesh>
  );
};

export default SpaceShip;
